"use client";

import { useEffect, useState } from "react";
import Link from "next/link";

interface CharityBreakdown {
  id: string;
  name: string;
  description: string | null;
  website_url: string | null;
  totalAmount: number;
  donationsCount: number;
  uniqueDonors: number;
}

interface DonationRecord {
  id: string;
  amount: number;
  percentage: number;
  source: string;
  charity_name: string;
  charity_id: string;
  donor_name: string;
  donor_email: string;
  created_at: string;
}

interface Metrics {
  totalDonationsAmount: number;
  totalDonationsCount: number;
  totalUniqueDonors: number;
  totalCharitiesSupported: number;
}

export default function AdminCharityPage() {
  const [metrics, setMetrics] = useState<Metrics | null>(null);
  const [charityBreakdown, setCharityBreakdown] = useState<CharityBreakdown[]>([]);
  const [donations, setDonations] = useState<DonationRecord[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [selectedCharity, setSelectedCharity] = useState<string>("all");

  async function loadCharityData() {
    setLoading(true);
    try {
      const res = await fetch("/api/admin/charity");
      const data = await res.json();
      if (res.ok) {
        setMetrics(data.metrics || null);
        setCharityBreakdown(data.charityBreakdown || []);
        setDonations(data.donations || []);
      }
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    loadCharityData();
  }, []);

  const filteredDonations = donations.filter((d) => {
    const matchesSearch =
      d.donor_name.toLowerCase().includes(search.toLowerCase()) ||
      d.donor_email.toLowerCase().includes(search.toLowerCase()) ||
      d.charity_name.toLowerCase().includes(search.toLowerCase());

    const matchesCharity =
      selectedCharity === "all" ? true : d.charity_id === selectedCharity;

    return matchesSearch && matchesCharity;
  });

  return (
    <main className="min-h-screen bg-slate-50 p-4 sm:p-6 lg:p-8 text-slate-900 dark:bg-[#070b12] dark:text-slate-100">
      <div className="mx-auto max-w-7xl space-y-8">
        {/* Header & Breadcrumb */}
        <div className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-200/80 pb-6 dark:border-slate-800/80">
          <div>
            <div className="flex items-center space-x-2">
              <span className="rounded-full bg-amber-500/10 px-3 py-1 text-xs font-bold text-amber-700 dark:text-amber-300">
                👑 Admin Control Center
              </span>
              <span className="text-xs text-slate-400">•</span>
              <span className="text-xs text-slate-500 dark:text-slate-400">
                Charity & Impact Audit
              </span>
            </div>

            <h1 className="mt-2 text-2xl sm:text-3xl font-black tracking-tight text-slate-950 dark:text-white">
              Charity Donations & Impact Fund 🎗️
            </h1>
            <p className="mt-1 text-sm text-slate-600 dark:text-slate-400">
              Complete transparency into all donations generated by golfers from sweepstakes entries and memberships.
            </p>
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={loadCharityData}
              disabled={loading}
              className="inline-flex items-center gap-2 rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-xs font-bold text-slate-700 shadow-xs hover:bg-slate-50 dark:border-slate-800 dark:bg-slate-900 dark:text-slate-300 dark:hover:bg-slate-800 cursor-pointer"
            >
              <svg className={`h-4 w-4 ${loading ? "animate-spin" : ""}`} fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
              </svg>
              Refresh Data
            </button>
            <Link
              href="/dashboard"
              className="rounded-xl bg-slate-950 px-4 py-2.5 text-xs font-bold text-white shadow-xs hover:bg-slate-800 dark:bg-emerald-600 dark:hover:bg-emerald-500"
            >
              ← Command Center
            </Link>
          </div>
        </div>

        {/* 4 Impact Summary KPI Cards */}
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {/* Card 1: Total Donated */}
          <div className="rounded-3xl border border-slate-200/80 bg-white p-6 shadow-sm dark:border-slate-800/80 dark:bg-[#0b101b]">
            <div className="flex items-center justify-between">
              <span className="text-xs font-black uppercase tracking-wider text-slate-500 dark:text-slate-400">
                Total Charity Raised
              </span>
              <span className="flex h-8 w-8 items-center justify-center rounded-xl bg-rose-500/10 text-rose-600 dark:bg-rose-950/60 dark:text-rose-400 text-sm">
                🎗️
              </span>
            </div>
            <p className="mt-3 text-3xl font-black tracking-tight text-rose-600 dark:text-rose-400">
              ₹{metrics ? metrics.totalDonationsAmount.toLocaleString("en-IN") : "0"}
            </p>
            <p className="mt-1 text-xs text-slate-500 dark:text-slate-400">
              100% verified community donations
            </p>
          </div>

          {/* Card 2: Donations Count */}
          <div className="rounded-3xl border border-slate-200/80 bg-white p-6 shadow-sm dark:border-slate-800/80 dark:bg-[#0b101b]">
            <div className="flex items-center justify-between">
              <span className="text-xs font-black uppercase tracking-wider text-slate-500 dark:text-slate-400">
                Donation Events
              </span>
              <span className="flex h-8 w-8 items-center justify-center rounded-xl bg-emerald-500/10 text-emerald-600 dark:bg-emerald-950/60 dark:text-emerald-400 text-sm">
                ❤️
              </span>
            </div>
            <p className="mt-3 text-3xl font-black tracking-tight text-slate-950 dark:text-white">
              {metrics ? metrics.totalDonationsCount : 0}
            </p>
            <p className="mt-1 text-xs text-slate-500 dark:text-slate-400">
              Total successful contributions
            </p>
          </div>

          {/* Card 3: Unique Donors */}
          <div className="rounded-3xl border border-slate-200/80 bg-white p-6 shadow-sm dark:border-slate-800/80 dark:bg-[#0b101b]">
            <div className="flex items-center justify-between">
              <span className="text-xs font-black uppercase tracking-wider text-slate-500 dark:text-slate-400">
                Contributing Members
              </span>
              <span className="flex h-8 w-8 items-center justify-center rounded-xl bg-blue-500/10 text-blue-600 dark:bg-blue-950/60 dark:text-blue-400 text-sm">
                👥
              </span>
            </div>
            <p className="mt-3 text-3xl font-black tracking-tight text-slate-950 dark:text-white">
              {metrics ? metrics.totalUniqueDonors : 0}
            </p>
            <p className="mt-1 text-xs text-slate-500 dark:text-slate-400">
              Golfers who chose a cause
            </p>
          </div>

          {/* Card 4: Causes Supported */}
          <div className="rounded-3xl border border-slate-200/80 bg-white p-6 shadow-sm dark:border-slate-800/80 dark:bg-[#0b101b]">
            <div className="flex items-center justify-between">
              <span className="text-xs font-black uppercase tracking-wider text-slate-500 dark:text-slate-400">
                Partner Charities
              </span>
              <span className="flex h-8 w-8 items-center justify-center rounded-xl bg-purple-500/10 text-purple-600 dark:bg-purple-950/60 dark:text-purple-400 text-sm">
                🏛️
              </span>
            </div>
            <p className="mt-3 text-3xl font-black tracking-tight text-slate-950 dark:text-white">
              {metrics ? metrics.totalCharitiesSupported : 0}
            </p>
            <p className="mt-1 text-xs text-slate-500 dark:text-slate-400">
              Active verified NGOs & Causes
            </p>
          </div>
        </div>

        {/* Breakdown by Charity */}
        <div>
          <h2 className="text-lg font-black tracking-tight text-slate-950 dark:text-white mb-4">
            Charity Distribution Overview
          </h2>
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {charityBreakdown.map((c) => (
              <div
                key={c.id}
                className="rounded-3xl border border-slate-200/80 bg-white p-6 shadow-sm dark:border-slate-800/80 dark:bg-[#0b101b] flex flex-col justify-between"
              >
                <div>
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-black uppercase tracking-wider text-emerald-600 dark:text-emerald-400">
                      Partner Cause
                    </span>
                    <span className="text-xs font-bold text-slate-400">
                      {c.donationsCount} donation{c.donationsCount === 1 ? "" : "s"}
                    </span>
                  </div>
                  <h3 className="mt-2 text-lg font-black text-slate-900 dark:text-white">
                    {c.name}
                  </h3>
                  <p className="mt-1 text-xs text-slate-500 dark:text-slate-400 line-clamp-2">
                    {c.description || "Dedicated to impactful community change and golfer-backed funding."}
                  </p>
                </div>

                <div className="mt-6 border-t border-slate-100 dark:border-slate-800/80 pt-4 flex items-center justify-between">
                  <div>
                    <span className="text-[10px] font-bold uppercase text-slate-400">Total Received</span>
                    <p className="text-xl font-black text-emerald-600 dark:text-emerald-400">
                      ₹{c.totalAmount.toLocaleString("en-IN")}
                    </p>
                  </div>
                  <span className="text-xs font-bold text-slate-500">
                    {c.uniqueDonors} donor{c.uniqueDonors === 1 ? "" : "s"}
                  </span>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Search & Filter */}
        <div className="flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="relative w-full sm:w-80">
            <input
              type="text"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder="Search donor name, email or charity..."
              className="w-full rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-xs text-slate-900 shadow-xs focus:border-emerald-500 focus:outline-none dark:border-slate-800 dark:bg-slate-900 dark:text-white"
            />
          </div>

          <div className="flex items-center gap-2 self-start sm:self-auto flex-wrap">
            <button
              onClick={() => setSelectedCharity("all")}
              className={`rounded-xl px-3.5 py-2 text-xs font-bold transition cursor-pointer ${
                selectedCharity === "all"
                  ? "bg-slate-950 text-white dark:bg-emerald-600 dark:text-white shadow-xs"
                  : "bg-white border border-slate-200 text-slate-600 hover:bg-slate-50 dark:border-slate-800 dark:bg-slate-900 dark:text-slate-400"
              }`}
            >
              All Charities ({donations.length})
            </button>
            {charityBreakdown.map((c) => (
              <button
                key={c.id}
                onClick={() => setSelectedCharity(c.id)}
                className={`rounded-xl px-3 py-2 text-xs font-bold transition cursor-pointer ${
                  selectedCharity === c.id
                    ? "bg-slate-950 text-white dark:bg-emerald-600 dark:text-white shadow-xs"
                    : "bg-white border border-slate-200 text-slate-600 hover:bg-slate-50 dark:border-slate-800 dark:bg-slate-900 dark:text-slate-400"
                }`}
              >
                {c.name}
              </button>
            ))}
          </div>
        </div>

        {/* Donation Transactions Table */}
        <div className="rounded-3xl border border-slate-200/80 bg-white shadow-sm dark:border-slate-800/80 dark:bg-[#0b101b] overflow-hidden">
          {loading ? (
            <div className="p-16 text-center text-slate-500">
              <div className="mx-auto h-6 w-6 animate-spin rounded-full border-2 border-emerald-500 border-t-transparent mb-2" />
              Loading donations data...
            </div>
          ) : filteredDonations.length === 0 ? (
            <div className="p-16 text-center">
              <div className="mx-auto mb-3 flex h-14 w-14 items-center justify-center rounded-2xl bg-slate-100 dark:bg-slate-800 text-2xl">
                🎗️
              </div>
              <h3 className="text-base font-bold text-slate-900 dark:text-white">
                No charity donations found
              </h3>
              <p className="mt-1 text-xs text-slate-500 dark:text-slate-400">
                When golfers contribute from sweepstakes entries or subscriptions, all donation records will be displayed here.
              </p>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-left text-sm">
                <thead className="border-b border-slate-200/80 bg-slate-50/70 text-xs font-bold uppercase tracking-wider text-slate-500 dark:border-slate-800/80 dark:bg-slate-900/50 dark:text-slate-400">
                  <tr>
                    <th className="px-6 py-4">Donor Golfer</th>
                    <th className="px-6 py-4">Charity Supported</th>
                    <th className="px-6 py-4">Donation Amount</th>
                    <th className="px-6 py-4">Contribution %</th>
                    <th className="px-6 py-4">Source</th>
                    <th className="px-6 py-4">Date Recorded</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 dark:divide-slate-800/60 font-medium">
                  {filteredDonations.map((d) => (
                    <tr key={d.id} className="hover:bg-slate-50/50 dark:hover:bg-slate-900/40 transition-colors">
                      <td className="px-6 py-4">
                        <div className="font-bold text-slate-950 dark:text-white">
                          {d.donor_name}
                        </div>
                        <div className="text-xs text-slate-400 font-mono">
                          {d.donor_email}
                        </div>
                      </td>
                      <td className="px-6 py-4 font-bold text-slate-800 dark:text-slate-200">
                        {d.charity_name}
                      </td>
                      <td className="px-6 py-4">
                        <span className="text-base font-black text-rose-600 dark:text-rose-400">
                          ₹{d.amount.toLocaleString("en-IN")}
                        </span>
                      </td>
                      <td className="px-6 py-4">
                        <span className="rounded-full bg-emerald-100 dark:bg-emerald-950/60 text-emerald-800 dark:text-emerald-300 font-black px-2.5 py-0.5 text-xs">
                          {d.percentage}%
                        </span>
                      </td>
                      <td className="px-6 py-4 text-xs font-semibold uppercase text-slate-500">
                        {d.source}
                      </td>
                      <td className="px-6 py-4 text-xs text-slate-500 dark:text-slate-400">
                        {new Date(d.created_at).toLocaleDateString("en-GB", {
                          day: "numeric",
                          month: "short",
                          year: "numeric",
                        })}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </div>
    </main>
  );
}
